version: "3.7"
services:
  app:
    container_name: api
    image: "leoozeballos/concesionaria:latest"
    ports:
      - "8080:8080"
    environment:
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/concesionaria"
      - "SPRING_DATASOURCE_USERNAME=postgres"
      - "SPRING_DATASOURCE_PASSWORD=docker"
    networks:
      - concesionaria
    restart: always

  front:
    container_name: front
    image: "leoozeballos/frontend-concesionaria:latest"
    ports:
      - "3000:3000"
    networks:
      - concesionaria
    restart: always

  db:
    image: "postgres:latest"
    container_name: local_pgdb
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "docker"
      POSTGRES_DB: "concesionaria"
    ports:
      - "5433:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - concesionaria
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@concesionaria.com
      PGADMIN_DEFAULT_PASSWORD: docker
    networks:
      - concesionaria
    volumes:
      - pgadmin-data:/var/lib/pgadmin

networks:
  concesionaria:
    driver: bridge

volumes:
  pgadmin-data: